### ISSUE TITLE
why are scripting and websocket disabled?

### ISSUE THREAD

**Issue by mohad12211** [ISSOtm/PKGBUILDs#1]
Hey! `aseprite-skia-bin` maintainer here, thank you for refactoring the PKGBUILD's, I learned some new stuff reading your patches!
one question, why exactly did you disable scripting and websocket? I compiled aseprite with scripting and websocket with no issues, 1.2.32

**Comment by ISSOtm** [comment]
I disabled them to pull in less dependencies (it may be compiling fine on your machine if the deps are already there, but it doesn't on mine) and to reduce the already fairly *large* build time. (IIRC, the libs pulled in by those features don't have any options to make them shared, and I was reluctant to apply more patches.)

I also believe that previous versions had no scripting support, or that it wasn't seeing much use, making that decision's impact low. But it's an "administrative" decision nonetheless, so my plan of action was to disable it until someone requested it, at which point we'd review the dependencies etc. again.

**Comment by ISSOtm** [comment]
Note: the package `aseprite` enabled the functionality at users' requests anyway. https://github.com/ImperatorStorm/PKGBUILDs/commit/8e61c3a6810514a85c20db63b955eaa334b30081
